name: Build and Deploy to GitHub Pages

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

  env:
    NODE_VERSION: '18'

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest

      steps:
        # Чекаут репозитория
        - name: Checkout code
          uses: actions/checkout@v4

        # Установка Node.js
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ env.NODE_VERSION }}
            cache: 'npm'

        # Установка зависимостей
        - name: Install dependencies
          run: npm ci

        # Проверка линтинга (опционально)
        - name: Run ESLint
          run: npm run lint
          if: always()

        # Сборка проекта
        - name: Build project
          run: npm run build
          env:
            BASE_URL: /my-new-project/ # Замените на имя вашего репозитория

        # Деплой на GitHub Pages
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          if: github.ref == 'refs/heads/main' # Деплой только из main
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
            keep_files: false # Очищать старые файлы
